### PR TITLE
Fix a bug & fetching of codes

### PR DESCRIPTION
**Pull request by oof2win2**
- Fixed a bug with the new API (`https://interclip.app/includes/api` was deprecated)
- Added functionality to fetch a code

### CODE REVIEW

**Review by filiptronicek — CHANGES_REQUESTED** [review]
The changes look great @oof2win2! Thanks a lot for them. I've been wanting to do this for a while. A couple of things that came to mind while reviewing:
- The margins on the <kbd>Receive</kbd> page could be a bit bigger, there's a lot of unused space
- I would change the action button according to what it's going to do: `Create a clip` or `Receive a clip`

**Comment by oof2win2** [comment]
So this is one of the revisions I thought of.
Screenshot 2021-10-01 at 23 27 03
Here is the other which I think looks better, the space below the button has been reduced. The only issue that I have with it is a weird bug, if I set the innerHTML of the link (output), it doesn't respect the `max-width` property anymore, and it just overflows as seen in the last image. What do you think?
Screenshot 2021-10-01 at 23 35 27
Screenshot 2021-10-01 at 23 37 43

**Comment by filiptronicek** [comment]
> Here is the other which I think looks better, the space below the button has been reduced. The only issue that I have with it is a weird bug, if I set the innerHTML of the link (output), it doesn't respect the `max-width` property anymore, and it just overflows as seen in the last image. What do you think?

Perhaps you could use [`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

**Comment by oof2win2** [comment]
Yay, that worked! Surprisingly, it works for extremely long URLs too (see code `kriwq`)

**Review by filiptronicek — APPROVED** [review]
LGTM, thanks for sticking with me, had to finish some other things first.

**Pull request merged**
